export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const EDIT_APPLICATION = "EDIT_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
export const FETCH_APPLICATION = "FETCH_APPLICATION";
export const FETCH_APPLICATIONS = "FETCH_APPLICATIONS";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
