export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const EDIT_APPLICATION = "EDIT_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
export const FETCH_APPLICATION = "FETCH_APPLICATION";
export const FETCH_APPLICATIONS = "FETCH_APPLICATIONS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const LOADING_USER = "LOADING_USER";
